### PR TITLE
added handling of absolute redirect paths

### PR DESCRIPTION
**Pull request by bentheiii**

### CODE REVIEW

**Comment by bentheiii** [comment]
fixes #52

**Review by masipcat — COMMENTED** [review]
I'm ok with the fix but it seems that updating starlette to 0.19 breaks `test_request_stream`

**Comment by bentheiii** [comment]
Yeah I tried my best but I can't figure out what the problem is, reverted starlette for now. Hopefully someone with more ASGI knowledge can come along down the line.

**Review by masipcat — COMMENTED** [review]
Do you mind updating the changelog and the version in setup.py? The rest looks good :)

**Review by masipcat — APPROVED** [review]

**Comment by masipcat** [comment]
version 1.4.11 released

**Pull request merged**
